export const FLASH_MESSAGE = {
   SUCCESS: "success",
   ERROR: "error",
   WARNING: "warning",
   INFO: "info",
   SEMESTER_CREATE: "Semestre criado com sucesso",
   SEMESTER_UPDATE: "Semestre atualizado com sucesso",
   SEMESTER_DELETE: "Semestre excluido com sucesso",
   SEMESTER_NOT_UPDATE: "Nao foi possivel atualizar o semestre",
   SEMESTER_NOT_DELETE: "Nao foi possivel excluir o semestre",
   EVENT_CREATE: "Evento criado com sucesso",
   EVENT_UPDATE: "Evento atualizado com sucesso",
   EVENT_DELETE: "Evento excluido com sucesso",
   EVENT_NOT_UPDATE: "Nao foi possivel atualizar o evento",
   EVENT_NOT_DELETE: "Nao foi possivel excluir o evento",
   EVENT_NOT_FOUND: "Nao foi possivel encontrar o evento",
   DISCIPLINE_CREATE: "Disciplina criada com sucesso",
   DISCIPLINE_UPDATE: "Disciplina atualizada com sucesso",
   DISCIPLINE_DELETE: "Disciplina excluida com sucesso",
   DISCIPLINE_NOT_UPDATE: "Nao foi possivel atualizar a disciplina",
   DISCIPLINE_NOT_DELETE: "Nao foi possivel excluir a disciplina",
   COURSE_PRICE_CREATE: "Preço criada com sucesso",
   COURSE_PRICE_UPDATE: "Preço atualizada com sucesso",
   COURSE_PRICE_DELETE: "Preço excluida com sucesso",
   COURSE_PRICE_NOT_UPDATE: "Nao foi possivel atualizar o Preço",
   COURSE_PRICE_NOT_DELETE: "Nao foi possivel excluir a Preço",
   COURSE_PRICE_NOT_FOUND: "Nao foi possivel encontrar o preço",
   PAYMENT_CREATE: "Pagamento criado com sucesso",
   PAYMENT_UPDATE: "Pagamento atualizado com sucesso",
   PAYMENT_DELETE: "Pagamento excluido com sucesso",
   PAYMENT_NOT_UPDATE: "Nao foi possivel atualizar o pagamento",
   PAYMENT_NOT_DELETE: "Nao foi possivel excluir o pagamento",
   STUDENT_CREATE: "Aluno criado com sucesso",
   STUDENT_UPDATE: "Aluno atualizado com sucesso",
   STUDENT_DELETE: "Aluno excluido com sucesso",
   STUDENT_NOT_UPDATE: "Nao foi possivel atualizar o aluno",
   STUDENT_NOT_DELETE: "Nao foi possivel excluir o aluno",
   STUDENT_NOT_FOUND: "Nao foi possivel encontrar o aluno",
   COURSE_CREATE: "Curso criado com sucesso",
   COURSE_NOT_CREATE: "Nao foi possivel criar o curso",
   COURSE_UNEXPECTED_ERROR: "Unable to create course",
   COURSE_UPDATE: "Curso atualizado com sucesso",
   COURSE_DELETE: "Curso excluido com sucesso",
   COURSE_NOT_UPDATE: "Nao foi possivel atualizar o curso",
   COURSE_NOT_DELETE: "Nao foi possivel excluir o curso",
   COURSE_NOT_FOUND: "Nao foi possivel encontrar o curso",
   FACULTIES_ASSIED: 'Professores listados com sucesso',
   FACULTIES_NOT_ASSIED: 'Ocorreu um erro ao listar o professores',
   FACULTIES_REMOVED: 'Professores removidos com sucesso',
   FACULTY_CREATE: "Professor criada com sucesso",
   FACULTY_UPDATE: "Professor atualizada com sucesso",
   FACULTY_DELETE: "Professor excluida com sucesso",
   FACULTY_NOT_UPDATE: "Nao foi possivel atualizar a Professor",
   FACULTY_NOT_DELETE: "Nao foi possivel excluir a Professor",
   FACULTY_NOT_FOUND: "Nao foi possivel encontrar a Professor",
} 